# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Behavior Tests

on:
  push:
    branches: ["main", "ability-categories"]
  pull_request:
    branches: ["main", "ability-categories"]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm i
      - run: npm run build --if-present
      - run: npm test:ci
        env:
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
